services:
  postgres:
    image: postgres:15-alpine
    container_name: feedback
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: on-failure

  redis:
    image: redis:7-alpine
    container_name: feedback-redis
    ports:
      - "6379:6379"
    restart: on-failure
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data

  celery_worker:
    build: .
    container_name: feedback-celery-worker
    command: celery -A src.celery_app worker --loglevel=info --concurrency=2
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_healthy
    restart: on-failure
    environment:
      - BASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - REDIS_URL=redis://redis:6379/0

  flower:
    build: .
    container_name: feedback-flower
    command: celery -A src.celery_app flower --port=5555
    env_file:
      - .env
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
    ports:
      - "5555:5555"
    depends_on:
      redis:
        condition: service_healthy
    restart: on-failure

volumes:
  postgres_data:
  redis_data: